### ISSUE TITLE
New dependencies

### ISSUE THREAD

**Issue by mottosso** [feather3d/feather#41]
Hey Richard,

I was looking into getting up to speed with Feaher again and noticed a few new dependencies, most prominently Vulkan. Vulkan was a showstopper for me on Linux unfortunately due to difficulties in getting setup with drivers. I'll see if I can give a Windows build another go, as I have Vulkan setup there already.

Also noticed freeglut and OpenGL Image (gli) as new requirements.

What do you think about maintaining a list of dependencies someplace, such as in the Wiki? I've gone ahead and updated the build instructions for Ubuntu, but it is not yet complete due to not being able to finish on my end.

**Comment by richardlayman** [comment]
Ubuntu should have all the vulkan drivers needed to build the application.
These are the packages that are loaded on my system:

- vulkan-headers 1.0.20160311-1
- vulkan-icd-loader 1.0.3.0-4
- vulkan-intel 0.0.2+2163+g097564b-1
- vulkan-validation-layers 1.0.3.0-4

Vulkan is currently only be used with the Vulture test application - which is totally isolated from Feather, so you don't even need to really build any of the vulkan code as of yet; if you commit out the below line from src/lib/CMakeList.txt it will build without Vulkan.

`add_subdirectory(core)`
`add_subdirectory(qml)`
`add_subdirectory(vulkan) # comment out this line`

Vulkan will not get added to the Feather until it passes all the tests in Vulture.

**Comment by mottosso** [comment]
Headers wasn't much of a problem, drivers were. As in graphics card drivers.

By the way, what's "Vulture"?

**Comment by richardlayman** [comment]
Is your issue finding the drivers or getting them to work?

Vulture is used for testing various Vulkan features and shaders with Feather's core scenegraph. It makes it so that I focus on vulkan issues without having to worring if it might be a issue with Feather causing a bug. Once all the testing is done I'll move feather_vulkan over to the main ui.

**Comment by mottosso** [comment]
> Is your issue finding the drivers or getting them to work?

Getting them to work.

1. It won't work in a VM
2. With dual-booting, installing binary beta drivers was tough. I then tried the native version through the "Additional Drivers" application in Ubuntu, but I had trouble getting any Vulkan sample up and running from there on. :(

Where can I find out more about Vulture? Google doesn't seem to give me anything on it.

**Comment by mottosso** [comment]
Oh, and about getting it running on Windows, there are too many [Linux-only dependencies](https://github.com/feather3d/feather/issues/13) at the moment and solving that is currently above my head. But I'm working on it!

**Comment by richardlayman** [comment]
There are no Linux-only libraries used in Feather, just need to modify CMake so that it can find the libraries and install in the correct location. I did put in some linux paths into the code, but that can be easily with a ifdef statement.

Currently my Vulkan code will only work with Linux since I took out all the Windows specific code to make smaller and easier to understand, but all that can be put back in.

This is the samples I used:
https://github.com/SaschaWillems/Vulkan
They all built and worked (within some limitations).

I wrote Vulture myself, it's just a ui for the feather_vulkan library.

If your only going to work on ui stuff, I would suggest to just disable vulkan the vulture in CMake; they won't effect you in anyway for awhile.

**Comment by mottosso** [comment]
Ok, then the barrier to entry is just too high for me at the moment.

I would expect it to build as-is, and tweak things afterwards. At this point, I have no way of validating the changes I make to get it up and running until it has **all** been fixed at once. That's more than I can bear..

For example, here's the todo list as I understand it.

1. Disable part of the project through CMake, a framework of which I know little
2. Redirect your local paths to mine
3. Replace Linux-only libraries (I mean dlfcn) with a Windows equivalent, neither of which I understand
4. Preserve cross-platform compatibility with `ifdef`

And here's what I'd consider a reasonable build guide, which Feather almost was a few months back.

1. Clone repo
2. Install dependencies
3. Build

I'll keep an eye out for when the project gets back to that point.
